export enum FeedbackTag {
  FIT_PERFECT = 'FIT_PERFECT',
  FIT_BAD = 'FIT_BAD',
  COLOR_GOOD = 'COLOR_GOOD',
  COLOR_BAD = 'COLOR_BAD',
  ITEM_MISMATCH = 'ITEM_MISMATCH',
  TPO_MISMATCH = 'TPO_MISMATCH'
}